# AWS SAM
Resources:
  notsafenotfair:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 10
      Environment:
        Variables:
          HTML_URL: 'see ./.env.json'
          PGHOST: 'see ./.env.json'
          PGPASSWORD: 'see ./.env.json'
          PGUSER: 'see ./.env.json'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
        Home:
          Type: Api
          Properties:
            Path: /
            Method: any
